#!/bin/sh

bash $HOME/.config/river/start.sh

riverctl focus-follows-cursor normal

riverctl map normal Super Tab focus-previous-tags

riverctl map normal Super Return spawn /usr/bin/alacritty
riverctl map normal Super+Shift Return spawn /usr/bin/kitty
riverctl map normal Super+Control Return spawn /usr/bin/warp-terminal

riverctl map normal Super D spawn '/usr/bin/ags -t applauncher'
riverctl map normal Super R spawn '/usr/bin/ags -q; ags'
# Super+Q to close the focused view
riverctl map normal Super C close

# Browser
riverctl map normal Super W spawn '/usr/bin/brave --enable-features=UseOzonePlatform --ozone-platform=wayland --use-gl=desktop --disable-features=UseChromeOSDirectVideoDecoder --enable-features=VaapiVideoDecoder'

# Utils
riverctl map normal Super V spawn '$HOME/.dotfiles/scripts/toggle_vpn.lua'
riverctl map normal Super X spawn '$HOME/.config/rofi/powermenu/type-4/powermenu.sh'
riverctl map normal Super M spawn '/usr/bin/alacritty --class floatcritty -e /usr/bin/ncmpcpp -c $HOME/.ncmpcpp/config'
riverctl map normal Super E spawn '/usr/bin/thunar'

# Screenshots
riverctl map normal Super Print spawn '$HOME/.dotfiles/scripts/gss.lua region'
riverctl map normal Super S spawn '$HOME/.dotfiles/scripts/gss.lua window'
riverctl map normal None Print spawn '$HOME/.dotfiles/scripts/gss.lua full'
riverctl map normal Super Q spawn '$HOME/.dotfiles/scripts/gss.lua aspect_visualizer'

# Wallpapers WBG
riverctl map normal Super U spawn '$HOME/.dotfiles/scripts/WBG.lua next'
riverctl map normal Super+Shift U spawn '$HOME/.dotfiles/scripts/WBG.lua prev'

# HyprEcko
riverctl map normal Super P spawn '/usr/bin/hyprpicker -a'
riverctl map normal Super L spawn '/usr/bin/gtklock'

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift P zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

ssds=('org.gnome.Loupe' 'Alacritty' 'dev.zed.Zed' 'thunar' 'uget-gtk' 'io.github.celluloid_player.Celluloid' 'nwg-look' 'dev.warp.Warp')

for it in "${ssds[@]}"; do
    riverctl rule-add -app-id "$it" ssd
done

riverctl rule-add -app-id 'brave-browser' tags 2

riverctl rule-add -app-id 'code-url-handler' tags 4
riverctl rule-add -app-id 'dev.zed.Zed' tags 4

riverctl rule-add -app-id 'thunar' tags 8

riverctl rule-add -app-id 'org.telegram.desktop' tags 32
riverctl rule-add -app-id 'discord' tags 32

riverctl rule-add -app-id 'io.github.celluloid_player.Celluloid' tags 64
riverctl rule-add -app-id 'vlc' tags 64

riverctl rule-add -app-id 'uget-gtk' tags 128

for i in $(seq 1 9); do
	tags=$((1 << ($i - 1)))

	# Super+[1-9] to focus tag [0-8]
	riverctl map normal Super $i set-focused-tags $tags

	# Super+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal Super+Shift $i set-view-tags $tags

	# Super+Control+[1-9] to toggle focus of tag [0-8]
	riverctl map normal Super+Control $i toggle-focused-tags $tags

	# Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
	# Eject the optical drive (well if you still have one that is)
	riverctl map $mode None XF86Eject spawn 'eject -T'

	riverctl map $mode None XF86AudioRaiseVolume spawn '/usr/bin/wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+'
	riverctl map $mode None XF86AudioLowerVolume spawn '/usr/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'

	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext spawn 'playerctl next'
done

# Set background and border color
riverctl background-color 0x181825
riverctl border-color-focused 0x8aadf4
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
